### ISSUE TITLE
Error in mobilenet v4 small config

### ISSUE THREAD

**Issue by Oichii** [d-li14/mobilenetv4.pytorch#3]
In mobilenetv4_conv_small in block_specs there is an error in number of filters and kernel size.
https://github.com/d-li14/mobilenetv4.pytorch/blob/f6c76734417845f1536d1e1065f37b2e4342efba/mobilenetv4.py#L172 

current: 
 

> ('conv_bn', 96, 3, 2),
> ('conv_bn', 64, 1, 1),

should be: 
 
> ('conv_bn', 3, 2, 96),
> ('conv_bn', 1, 1,  64),

**Comment by d-li14** [comment]
@Oichii Thank you for pointing it out.
